### ISSUE TITLE
datatransferkit@master issue on macos

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#141] opened 2021-06-24 16:37 UTC
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6710813/spack-build-out.txt)

```
ref: balay/xsdk-develop, c945a684b2714c332f2c8db9eac6e554e86cc23c
 python3 ./bin/spack install --fail-fast -j6 xsdk@develop+trilinos~butterflypack~heffte%apple-clang@12.0.0 fflags=-fallow-argument-mismatch
```

**Comment by masterleinad** [comment] 2021-07-09 16:29
Looks like https://github.com/trilinos/trilinos/commit/3bcdcb8155ba4c840529bad25d0410b7bebea1b8 broke this.

**Comment by masterleinad** [comment] 2021-07-09 19:03
Fixed by https://github.com/trilinos/Trilinos/pull/9409 and https://github.com/ORNL-CEES/DataTransferKit/pull/600.

**Comment by balay** [comment] 2021-07-09 19:54
@masterleinad Thanks! A manual test with the above 2 patches gets the build going [on one of the linux tests]!

I'll attempt a full test - but this will take a while to complete

**Comment by balay** [comment] 2021-07-09 19:57
https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/334683634

**Comment by balay** [comment] 2021-07-09 23:15
I'm seeing a different build error on MacOS
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1413706279
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6794258/spack-build-out.txt)

**Comment by masterleinad** [comment] 2021-07-12 16:42
> I'm seeing a different build error on MacOS
> [gitlab.com/xsdk-project/spack-xsdk/-/jobs/1413706279](https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1413706279)
> [spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6794258/spack-build-out.txt)

Can you give me some instructions for reproducing the failure?

**Comment by balay** [comment] 2021-07-12 16:52
Well the build is on an Intel/Mac with not the latest xcode-command-line-tools [don't know if this will make a difference], and gfortran (and some build tools - don't know if this will make a difference) from brew.

```
xsdk@kpro ~ % sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1030
xsdk@kpro ~ % clang --version |head -1
Apple clang version 12.0.0 (clang-1200.0.32.2)
xsdk@kpro ~ % gfortran --version |head -1
GNU Fortran (Homebrew GCC 11.1.0_1) 11.1.0
```
And the general build is with:

```
git clone https://github.com/spack/spack
cd spack
git checkout balay/xsdk-develop
<setup spack> i.e run '/bin/spack compiler find', and make sure compilers.yaml has clang/clang++/gfortran for 'apple-clang@12.0.0' or equivalent version
python3 ./bin/spack install --fail-fast -j6 xsdk@develop~alquimia+trilinos %apple-clang@12.0.0 fflags=-fallow-argument-mismatch
```
Attaching spack config files used here..
[compilers.yaml.txt](https://github.com/xsdk-project/xsdk-issues/files/6803096/compilers.yaml.txt)
[packages.yaml.txt](https://github.com/xsdk-project/xsdk-issues/files/6803097/packages.yaml.txt)

I'll retry with a clean packages file - and see how that goes [with the above compilers]

**Comment by balay** [comment] 2021-07-12 19:49
I've run this on a different box [with similar osx/xcode version]
```
balay@ypro spack % sw_vers                    
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1030
balay@ypro spack % clang --version |head -1   
Apple clang version 12.0.0 (clang-1200.0.32.2)
balay@ypro spack % gfortran --version |head -1
GNU Fortran (Homebrew GCC 10.2.0) 10.2.0
```
  
with a fresh clone of spack [and fresh `spack compiler find`] - i.e  no packages.yaml. And used the following command [to avoid building other xsdk packages]
```
balay@ypro spack % nice python3 ./bin/spack install --fail-fast -j16 datatransferkit@master ^trilinos@develop+hypre+superlu-dist+metis+hdf5~mumps+boost~suite-sparse+tpetra+nox+ifpack2+zoltan2+amesos2~exodus~dtk+intrepid2+shards+stratimikos gotype=int cxxstd=14 ^mpich ^netlib-lapack
```
Attaching the build log [with errors]

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/6804021/spack-build-out.txt)

**Closed as completed** 2021-09-27 14:50 UTC
Labels: xsdk-0.7.0-release
