### ISSUE TITLE
trilinos@develop failure (with superlu_dist) on %gcc@9.2.0 

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#168] opened 2022-06-22 18:06 UTC
ref: ./bin/spack install --fail-fast -j16 xsdk@develop%gcc@9.2.0 ^netlib-lapack@3.9.1
```
/data/balay/spack.x/spack-stage/spack-stage-trilinos-develop-wq5gxylnbq4o6iyys64z474ehehfg3oq/spack-src/packages/amesos2/src/Amesos2_Superludist_FunctionMap.hpp:151:24: error: invalid conve\
rsion from 'SLUD::int_t' {aka 'int'} to 'SLUD::superlu_dist_options_t*' [-fpermissive]
  151 |       SLUD::D::pdgstrs(n, lu_struct, scale_perm_struct, grid, B, l_numrows,
      |                        ^
      |                        |
      |                        SLUD::int_t {aka int}

```
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/8960321/spack-build-out.txt)

**Comment by liuyangzhuan** [comment] 2022-06-22 18:33
Hi, @xiaoyeli, the problem is due to this commit [2c81a22ef7ace420664c4de3896e38394ca97826](https://github.com/xiaoyeli/superlu_dist/commit/2c81a22ef7ace420664c4de3896e38394ca97826)
, which changes the APIs of many routines, apparently trillinos uses SuperLU's internal functions. Not sure if we should ask trillinos to update the interface, as these changes have not been reflected in any superlu release yet.

**Comment by keitat** [comment] 2022-06-22 20:20
@liuyangzhuan  Is it official change in the new version (8.0.0)?  We have had a few changes in Amesos2 source  (Trilinos' sparse direct solvers packages) for the last version of SuperLU_DIST.   `pdgstrs` will be used in Amesos2 independently so that we can separate factorization and triangular solution steps.  As you may know, some applications need many triangular solve calls with the same coefficient matrix (DD, UQ, etc.)

**Comment by keitat** [comment] 2022-06-22 20:22
@jwillenbring Should I talk to Amesos2 developers to add another `#ifdef` blocks for the new SuperLU_DIST?

**Comment by liuyangzhuan** [comment] 2022-06-22 20:25
Sorry I was wrong saying the new interface is not in released versions. Indeed, it's changed since 8.0.0.

**Comment by jwillenbring** [comment] 2022-06-22 21:37
@keitat I think that would be a good approach.

**Comment by xiaoyeli** [comment] 2022-06-26 19:57
@keitat @jwillenbring  It's a good idea to update Amesos2 to version 8.0.
A lot of routines added the input "options" argument, for flexible parameter settings.
The new features and parameters are summarized in this users' guide:
https://portal.nersc.gov/project/sparse/superlu/toms_release.pdf

Version 8.0 release note is here:
https://github.com/xiaoyeli/superlu_dist/releases/tag/v8.0.0

**Comment by keitat** [comment] 2022-06-27 21:57
@xiaoyeli @balay @jwillenbring 

The change in Amesos2 is currently in PR.  https://github.com/trilinos/Trilinos/pull/10673

During this activity, I found that the header comments (describing the API usage) for the individual functions in SuperLU_DIST 8.0.0 have not been updated.  It's not urgent, but the users will appreciate to have a new version.

For example:

```
/*! \brief
 *
 * <pre>
 * Purpose
 * =======
 *
 * pdgstrs_Bglobal solves a system of distributed linear equations
 * A*X = B with a general N-by-N matrix A using the LU factorization
 * computed by pdgstrf.
 *
 * Arguments
 * =========
 *
 * n      (input) int (global)
 * B      (input/output) double*
 *        On entry, the right-hand side matrix of the possibly equilibrated
 *        and row permuted system.
 *        On exit, the solution matrix of the possibly equilibrated
 *        and row permuted system if info = 0;
 *
 *        NOTE: Currently, the N-by-NRHS  matrix B must reside on all
 *              processes when calling this routine.
 *
 * ldb    (input) int (global)
 *        Leading dimension of matrix B.
 *
 * nrhs   (input) int (global)
 *        Number of right-hand sides.
 *
 * stat   (output) SuperLUStat_t*
 *        Record the statistics about the triangular solves.
 *        See util.h for the definition of 'SuperLUStat_t'.
 *
 * info   (output) int*
 *         = 0: successful exit
 *         < 0: if info = -i, the i-th argument had an illegal value
 * </pre>
 */

void
pdgstrs_Bglobal(superlu_dist_options_t *options, int_t n,
                dLUstruct_t *LUstruct, gridinfo_t *grid,
                double *B, int_t ldb, int nrhs,
                SuperLUStat_t *stat, int *info)


```

**Comment by xiaoyeli** [comment] 2022-06-27 22:01
@keitat  Thanks!  I'll update the leading comments soon.

**Comment by xiaoyeli** [comment] 2022-07-06 01:36
@keitat  I have updated the leading comments of various routines. These are in the new release 8.1.0.  There are no interface changes compared to 8.0.0

**Comment by balay** [comment] 2022-07-08 03:22
Just a note - these errors persist. add the current build log here.
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/9068691/spack-build-out.txt)

**Comment by keitat** [comment] 2022-07-11 16:58
The code change in Trilinos has been merged to the develop branch.  

https://github.com/trilinos/Trilinos/pull/10673

**Closed as completed** 2023-08-03 16:56 UTC
Labels: pkg-trilinos, xsdk-develop
