### ISSUE TITLE
sundials@6.4.1 failure with latest ginkgo (develop) changes.

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#200] opened 2022-11-01 02:06 UTC
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/9905689/spack-build-out.txt)

current ginko development commit:
```
commit c1f8bd4ebc1096c977c6044a6f5531a715e533ae (HEAD -> develop, origin/develop, origin/HEAD)
Merge: cff97422ca b59a9dd7f1
Date:   Mon Oct 31 22:01:26 2022 +0100
```
Switching to earlier snapshot - build fails again. I'm confused. These xsdk builds worked yesterday - so this 'oct 5' commit was pushed today?

```
commit 06b1b4af6904994d5724c38b8a8923a71560aa70
Merge: f90097e220 d477926447
Date:   Wed Oct 5 08:51:15 2022 +0200
```
retry with earlier snapshot - the build goes through
```
commit f90097e22020686edfd41a64be2ba3c209388652
Merge: 8ec975700c 9cdd7d0510
Date:   Wed Sep 28 17:20:19 2022 +0200
```

For now will switch to `sundials~ginkgo`

**Comment by balay** [comment] 2022-11-01 15:18
This failure is also reflected in sundials@develop build

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/682150392

**Comment by balos1** [comment] 2022-11-01 15:48
Looks like ginkgo changed something that effects sundials. We won't be able to fix it on the sundials end for the xsdk release so `sundials~ginkgo` is fine unless sundials with ginkgo@develop starts working again by the time they do their releaae.

**Comment by balos1** [comment] 2022-11-01 16:06
@hartwiganzt @pratikvn could someone from Ginkgo take a look at this?

**Comment by pratikvn** [comment] 2022-11-01 16:15
I'm having a look. We will try to resolve it from the Ginkgo side.

**Comment by pratikvn** [comment] 2022-11-02 10:54
Update: We have figured out the issue and we will have a PR to fix it in Ginkgo develop soon. I have confirmed that the fix works with the SUNDIALS release branch as well.

**Comment by tcojean** [comment] 2022-11-03 15:50
The fix was merged

**Comment by balay** [comment] 2022-11-03 15:58
Thanks! will give it a go now

**Comment by balay** [comment] 2022-11-04 05:17
https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/685059053

The sundials+ginkgo build is clean now

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/685059053

**Closed as completed** 2022-11-04 15:06 UTC
Labels: pkg-sundials, xsdk-0.8.0-release, gitlab-ci-failure, pkg-ginkgo
