### ISSUE TITLE
exago build failure with intel compilers

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#220] opened 2023-08-29 18:36 UTC
ref: https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/4969753954

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/12468120/spack-build-out.txt)

**Comment by cameronrutherford** [comment] 2023-08-30 16:19
I don't understand what is going on here and cannot reproduce.

| Source Code | CI Error Line |
| --- | --- |
| https://github.com/pnnl/ExaGO/blob/develop/src/opflow/interface/opflowoutput.cpp#L34 | https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/4969753954#L1578 |
| https://github.com/pnnl/ExaGO/blob/develop/src/opflow/interface/opflowoutput.cpp#L37 |  https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/4969753954#L1595 |

I have added ExaGO GitHub source code references in `exago@develop` that correspond to the build failures. These lines call `.c_str()` where I linked, and these are changes added 5 months ago, so not quite sure what is going wrong here.

- Is the right ExaGO source code being used?
- Is there a way to add the concretization/spec being installed of ExaGO to the build logs? Spent a little time guessing as to what the actual used build config was...

**Comment by balay** [comment] 2023-08-30 17:54
> Is the right ExaGO source code being used?

You can try out a build with:  https://gitlab.com/xsdk-project/spack-xsdk/-/tree/xsdk-1.0.0

Where its using:
```
+    version("1.6.0", branch="main", submodules=True)
```

[with  dependencies on newer versions of hiop, petsc added]

So `main` is used here. Is `develop` the branch to use?

> Is there a way to add the concretization/spec being installed of ExaGO to the build logs

Attaching `spck spec` this build.

[spec.log](https://github.com/xsdk-project/xsdk-issues/files/12478800/spec.log)

**Comment by cameronrutherford** [comment] 2023-08-30 20:00
> > Is the right ExaGO source code being used?
> 
> You can try out a build with: https://gitlab.com/xsdk-project/spack-xsdk/-/tree/xsdk-1.0.0
> 
> Where its using:
> 
> ```
> +    version("1.6.0", branch="main", submodules=True)
> ```
> 
> [with dependencies on newer versions of hiop, petsc added]
> 
> So `main` is used here. Is `develop` the branch to use?
> 
> > Is there a way to add the concretization/spec being installed of ExaGO to the build logs
> 
> Attaching `spck spec` this build.
> 
> [spec.log](https://github.com/xsdk-project/xsdk-issues/files/12478800/spec.log)

Main has this bug, but develop does not. Please use develop, and we will try and get a release once we have fully moved over to GitHub.

**Comment by balay** [comment] 2023-08-31 13:03
Switching to 'develop' branch - I still get a failure..

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/4987095719

**Comment by cameronrutherford** [comment] 2023-09-05 20:33
Okay apologies for taking so long to get to this. We now have better compiler flags in our internal gcc pipelines that catch this type of issue and so hopefully this isn't as much of a problem moving forward.

Try again with latest exago@develop in GitHub and you should be good to go.

**Comment by balay** [comment] 2023-09-14 16:01
To update - exago builds continue to fail.

- https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5083134110
- https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5083134106
etc.

**Comment by balay** [comment] 2023-09-14 18:50
BTW: Forgot to mention the above 2 failures are with gcc. Perhaps they worked before? 

The intel builds also fail - for ex: https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/5089552335

**Comment by cameronrutherford** [comment] 2023-09-26 16:38
@balay we now have GitHub action pipelines that catch these build failures before xSDK pipelines catch them (hopefully).

`exago@develop` now has a fix that should let the pipelines go through, and with spack PR https://github.com/spack/spack/pull/40188, you can also build `exago~tests` in situations like this to avoid the problem altogether.

**Comment by cameronrutherford** [comment] 2023-09-28 18:33
Closing as latest pipelines are going through just fine. Need to create a new issue for gcc@11+ compilation issues

**Closed as completed by cameronrutherford** 2023-09-28 18:33 UTC
Labels: xsdk-1.0.0-release
